Sholja/styled-react-ui-libs

package.json, src/components/index.js
- There were a few components that were not included in the export of the module. Now, they should be all there.
=> Added missing components to export

package.json, src/components/alert/alert.js, src/components/card/card.js
- There was an issue with some of the default props of the "Card" component. Now the issue should be resolved.
=> Fixed props passed to the card component

package.json, src/components/button/button.js
- Fixed issue with disabled button style not applied.
=> Buttons disabled fix

package.json, src/components/default-input/default-input-styles.js, src/components/default-input/default-input.js, src/components/default-input/default-input.stories.js, yarn.lock
- Adjusted the default input component.
=> Default input adjustment

package.json, src/components/default-input/default-input.js
- Fixed issue with object assing on styles on the default input component.
=> Default input assign issue

package.json, src/components/alert/alert.js, src/components/button/button.js, src/components/card/card.js, src/components/default-input/default-input.js, src/components/default-radio/default-radio.js, src/components/default-select/default-select.js, src/components/default-textarea/default-textarea.js, src/components/footer/footer.js, src/components/header/header.js, src/components/hyperlink/hyperlink.js, src/components/table/table-body-row.js, src/components/table/table-body.js, src/components/table/table-head-row.js, src/components/table/table-head.js, src/components/table/table-row.js, src/components/table/table.js, src/components/text/text.js, src/components/unordered-list/unordered-list.js, yarn.lock
- Added get theme module so that components don't throw an error if the theme is not passed correctly.
=> Get theme props adjustment

package.json, src/components/empty-state/empty-state.js, yarn.lock
- Removed unnecessary Link component from the Empty State component. Now, it's replaced with the Hyperlink component from the module.
=> Empty state component adjustment

package.json, src/components/modal/modal.js
- Added styles to be passed to the close button in the modal.
=> Modal adjustment

package.json, src/components/modal/modal.js
- Fixed issue with close modal.
=> Modal close fix

package.json, src/components/tabs/tabs.js, src/components/tabs/tabs.stories.js, src/components/tabs/tabs.test.js, src/theme/styles/colors.js, src/theme/styles/fonts.js
- Implemented the tabs component. Included tests with the component.
=> Tabs component

package.json, src/components/default-checkbox/default-checkbox-styles.js, src/components/default-checkbox/default-checkbox.js, src/components/default-checkbox/default-checkbox.stories.js, src/components/default-checkbox/default-checkbox.test.js, src/theme/styles/colors.js
- Implemented the default checkbox component. Tests and storybook included in the project.
=> Default Checkbox

package.json, src/components/button/button.js, src/components/default-input/default-input.js, src/theme/styles/colors.js
- Adjusted button styles.
- Added readOnly styles for input.
=> Button and input adjustment

package.json, src/components/default-textarea/default-textarea.js
- Adjusted the textarea component to expect the placeholder prop.
=> Textarea adjustment

package.json, src/components/default-select/default-select.js, src/components/default-textarea/default-textarea.js
- Adjusted the default select and textarea components so that the error style overrides the default styles.
=> Default select and textarea style adjustment

package.json, src/components/default-radio/default-radio-styles.js, src/components/default-radio/default-radio.js
- Adjusted the radio button component to expect the label styles in props.
=> Radio button styles

package.json, src/components/default-radio/default-radio.js
- Override prop styles for the replacement input in the radio button component.
=> Radio button style adjustment

package.json, src/components/button/button.js, src/components/default-input/default-input.js, src/components/default-input/default-input.stories.js, src/components/default-radio/default-radio.js, src/components/upload-button/upload-button.js, src/theme/styles/colors.js, src/theme/styles/inputs.js
- Adjustments to inputs UI.
- Adjustment to upload button.
=> Multiple adjustments

package.json, src/components/tabs-selector/tabs-selector.js, src/components/tabs-selector/tabs-selector.stories.js, src/components/tabs-selector/tabs-selector.test.js
- Implemented the tabs selector component.
=> Tabs selector component

package.json, src/components/index.js, src/components/tabs-selector/tabs-selector.js
- Added export tabs selector component from the module.
=> Export tabs selector component

package.json, src/components/tabs/tabs.js
- Prop types adjustments to the Tabs component.
- Added key for mapping tabs to remove the error.
=> Tabs component adjustment

package.json, src/components/index.js, src/components/upload-button/upload-button.js, src/components/vertical-timeline/vertical-timeline-constants.js, src/components/vertical-timeline/vertical-timeline-helpers.js, src/components/vertical-timeline/vertical-timeline-item.js, src/components/vertical-timeline/vertical-timeline.js, src/components/vertical-timeline/vertical-timeline.stories.js
- Implemented the vertical timeline component.
=> Vertical timeline component

package.json, src/components/vertical-timeline/vertical-timeline-item.js
- Adjusted the UI of the vertical timeline component.
=> Vertical timeline component adjustment

package.json, src/components/vertical-timeline/vertical-timeline.js
- Fixed onClick in vertical timeline component.
=> Vertical timeline component adjustments

package.json, src/components/vertical-timeline/vertical-timeline-item.js
- Fixed issue with vertical timeline component when the subtitle or title is not passed.
=> Vertical timeline fix

package.json, src/components/default-checkbox/default-checkbox.js
- Override style of the label in the default checkbox component.
=> Default checkbox adjustment

package.json, src/components/default-input/default-input.js, src/components/default-input/default-input.stories.js, src/components/default-textarea/default-textarea.js
- Adjusted the default input and textarea components.
=> Default input and textarea adjustments

src/components/iframe/iframe.js, src/components/iframe/iframe.stories.js, src/components/iframe/iframe.test.js
=> iframe component initialize

package.json, src/components/modal/modal.js
- Adjusted padding on the modal title.
=> Modal title adjustment

src/components/index.js
- Export Iframe component from the lib
=> Export Iframe component from the lib

package.json, src/components/default-checkbox/default-checkbox.js
- Fixed issue with the default checkbox showing error when the form is loaded.
=> Default checkbox fix

src/theme/styles/buttons.js
- Fixed issue with missing hover styles on the button component.
=> Button hover styles

src/common/helpers.js, src/components/horizontal-timeline/horizontal-timeline.js, src/components/horizontal-timeline/horizontal-timeline.stories.js, src/components/index.js
- Implemented the horizontal timeline component.
=> Horizontal timeline component

package.json, src/components/horizontal-timeline/horizontal-timeline.js
- Fixed moving text on the horizontal timeline component.
=> Horizontal timeline fix

package.json, src/components/upload-button/upload-button.js
- Fixed issue with the upload button not triggering onChange function a second time.
=> Fixed issue with uplod button

package.json, src/components/images-expand/images-expand.js
- Added `alt` attribute to the image.
=> Image expand adjustment

package.json, src/components/button/button.js, src/components/default-input/default-input.js, src/components/default-select/default-select.js, src/components/default-textarea/default-textarea.js, src/components/modal/modal.js, src/theme/styles/colors.js
- Multiple UI adjustments to the components.
=> UI adjustments

package.json, src/components/default-select/default-select.js
- Pass props for the wrapper div around the dropdown.
=> Default select adjustment

package.json, src/components/default-input/default-input.js, src/components/default-input/default-input.stories.js
- Added new input type, input with label inside the input.
=> Input adjustments

package.json, src/components/custom-checkbox/custom-checkbox.js, src/components/default-checkbox/default-checkbox.js, src/components/default-input/default-input.js, src/components/default-radio/default-radio.js, src/components/default-select/default-select.js, src/components/default-textarea/default-textarea.js
- Adjusted error styles on all inputs.
=> Default inputs adjustments

package.json, src/components/default-input/default-input.js
- Override all styles to the default input component.
=> Default input override

package.json, src/components/paging/paging-item.js, src/components/paging/paging.js
- Adjusted paging component to accept props so that it's easily adjustable.
=> Paging component adjustment

package.json, src/components/default-select/default-select.js
- Fixed issue with error styles staying active if the select input is valid.
=> Default select error styles fix

package.json, src/components/custom-checkbox/custom-checkbox.js
- Pass styles object to the icon of the custom checkbox component.
=> Custom checkbox adjustment
